[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pay = "DTX9HCuLLnu7tkoi7mfbBYth6uzCnVG87X2U5p1cJMEH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./key/testKeypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
